# KOReader RSS wake integration
# version: 1
start on started lab126
stop on stopping lab126
respawn
script
    lipc-wait-event com.lab126.powerd wakeupFromSuspend
    @BACKEND@ --db @DATABASE@ refresh --budget @BUDGET@ --reason wake
end script
